### ISSUE TITLE
Fastify 4 compatibility issue

### ISSUE THREAD

**Issue by sinasalek** [fastify/point-of-view#318]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0-rc.3

### Plugin version

6.2.0

### Node.js version

16

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 10

### Description

It's complaining about version mismatch

FastifyError [Error]: fastify-plugin: point-of-view - expected '3.x' fastify version, '4.0.0-rc.3' is installed
    at Object.checkVersion (C:\Users\Sina\Work\Projects\Snöball\Application\snoball_server\node_modules\fastify\lib\pluginUtils.js:108:11)
    at Object.registerPlugin (\node_modules\fastify\lib\pluginUtils.js:123:16)
    at Boot.override (\node_modules\fastify\lib\pluginOverride.js:28:57)
    at Plugin.exec (\node_modules\avvio\plugin.js:80:33)
    at Boot.loadPlugin (\node_modules\avvio\plugin.js:273:10)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'FST_ERR_PLUGIN_VERSION_MISMATCH',
  statusCode: 500
}

### Steps to Reproduce

Install fastify 4 and the current version of point-of-view

**Comment by TTPO100AJIEX** [comment]
As fastify 4 is not the latest version (next), you should also install point-of-view next, not latest.

**Comment by sinasalek** [comment]
Just ignore this it was another package that was using an old version of this package as dependency. tx for the quick reply
