### ISSUE TITLE
TypeError: reply.view is not a function

### ISSUE THREAD

**Issue by victor0801x** [fastify/point-of-view#50]
I separate and registe rendering config in other file. 
```js
// marko_conf.js
const path = require("path");
module.exports = async (fastify, opts) => {
	fastify.register(require("point-of-view"), {
		engine: {
			marko: require("marko"),
		},
		includeViewExtension: false,
		templates: path.join(__dirname, "./templates")
	});
};
```
```js
// app.js
const fastify = require("fastify")();

fastify.register(require("./marko_conf.js"));
fastify.get("/", (req, reply) => {
	reply.view("index.marko", { text: "hi" });
});

fastify.listen(3000);
```

```

/home/jimmy/Desktop/test/app.js:7
	reply.view("index.marko", { text: "hi" });
	      ^
TypeError: reply.view is not a function
    at Object.fastify.get (/home/jimmy/Desktop/test/app.js:7:8)
    at preHandlerCallback (/home/jimmy/Desktop/test/node_modules/fastify/lib/handleRequest.js:88:30)
    at handler (/home/jimmy/Desktop/test/node_modules/fastify/lib/handleRequest.js:72:5)
    at handleRequest (/home/jimmy/Desktop/test/node_modules/fastify/lib/handleRequest.js:22:5)
    at onRunMiddlewares (/home/jimmy/Desktop/test/node_modules/fastify/fastify.js:346:5)
    at middlewareCallback (/home/jimmy/Desktop/test/node_modules/fastify/fastify.js:334:7)
    at Object.routeHandler [as handler] (/home/jimmy/Desktop/test/node_modules/fastify/fastify.js:224:7)
    at Router.lookup (/home/jimmy/Desktop/test/node_modules/find-my-way/index.js:265:17)
    at Server.emit (events.js:180:13)
    at parserOnIncoming (_http_server.js:642:12)
```
but, if I regist in the same file that will work

**Comment by mcollina** [comment]
You will need to use fastify-plugin if you define it in a separate file.

**Comment by victor0801x** [comment]
Thanks for quickly res.

**Comment by Bezlepkin** [comment]
Same issue.

My main.ts file

```
import path from 'node:path';
import chalk from 'chalk';
import fastify, { FastifyRequest as Request, FastifyReply as Response } from 'fastify';
import fastifyView from '@fastify/view';

const server = fastify({
  logger: false,
});

const port = 3000;

server.register(require('@fastify/cors'), { origin: '*' });
server.register(require('@fastify/static'), {
  root: path.join(__dirname, '..', 'public'),
});

server.register(fastifyView, {
  engine: {
    handlebars: require('handlebars'),
  },
  root: path.join(__dirname, '..', 'templates'),
  layout: 'layouts/main.hbs',
  viewExt: 'hbs',
  propertyName: 'render',
  defaultContext: {
    dev: process.env.NODE_ENV === 'development',
  },
  options: {},
});

// welcome page handler
server.get('/', (req: Request, res: Response) => {
  res.view('welcome/index.hbs');
});
...
```
